const demoSurvey: SurveyType = {
	_id: 'demo-survey',
	title: 'Customer Satisfaction Survey',
	description:
		'Help us improve our service by sharing your feedback. This should only take 2-3 minutes.',
	components: [
		{
			id: 'name',
			type: 'text-input',
			label: 'What is your name?',
			required: true,
			placeholder: 'Enter your full name',
			icon: 'this',
			name: 'TextBox',
		},
		{
			id: 'email',
			type: 'email',
			label: 'Email address',
			required: true,
			placeholder: 'you@example.com',
			icon: 'this',
			name: 'TextBox',
		},
		{
			id: 'divider-1',
			type: 'divider',
			icon: 'this',
			name: 'TextBox',
		},
		{
			id: 'heading-1',
			type: 'heading',
			label: 'Your Experience',
			icon: 'this',
			name: 'TextBox',
		},
		{
			id: 'satisfaction',
			type: 'star-rating',
			label: 'How would you rate your overall experience?',
			icon: 'this',
			name: 'TextBox',
			required: true,
			max: 5,
		},
		{
			id: 'nps',
			type: 'nps',
			label: 'How likely are you to recommend us to a friend?',
			icon: 'this',
			name: 'TextBox',
			description: 'On a scale of 0-10',
			required: true,
		},
		{
			id: 'service-quality',
			type: 'multiple-choice',
			label: 'How would you describe our service quality?',
			required: true,
			options: ['Excellent', 'Good', 'Average', 'Poor', 'Very Poor'],
			icon: 'this',
			name: 'TextBox',
		},
		{
			id: 'features',
			type: 'checkboxes',
			label: 'Which features do you use most often? (Select all that apply)',
			icon: 'this',
			name: 'TextBox',
			options: [
				'Dashboard',
				'Reports',
				'Analytics',
				'Integrations',
				'Mobile App',
			],
		},
		{
			id: 'mood',
			type: 'emoji',
			label: 'How do you feel about our product?',
			icon: 'this',
			name: 'TextBox',
			required: true,
			options: ['😢', '😕', '😐', '🙂', '😄'],
		},
		{
			id: 'continue',
			type: 'yes-no',
			label: 'Would you continue using our service?',
			icon: 'this',
			name: 'TextBox',
			required: true,
		},
		{
			id: 'divider-2',
			type: 'divider',
			icon: 'this',
			name: 'TextBox',
		},
		{
			id: 'heading-2',
			type: 'heading',
			label: 'Additional Feedback',
			icon: 'this',
			name: 'TextBox',
		},
		{
			id: 'improvements',
			type: 'textarea',
			label: 'What improvements would you like to see?',
			icon: 'this',
			name: 'TextBox',
			placeholder: 'Share your thoughts...',
			required: false,
		},
		{
			id: 'frequency',
			type: 'dropdown',
			label: 'How often do you use our product?',
			required: true,
			options: ['Daily', 'Weekly', 'Monthly', 'Rarely'],
			icon: 'this',
			name: 'TextBox',
		},
	],
};

export { demoSurvey };
